[Variables]
;Please put your location code of OpenWeatherMap below, e.g: London, GB is 2643743.
;You can check it on OpenWeatherMap.com. Search for your city and the id will be in the url 
;e.x. https://openweathermap.org/city/2643743

LocationCode=

;You also have to get a free API key by registering

ApiKey=

; Select which version of the calendar you want
; Valid options:
;
;   0 - Vanilla - Standard Persona 5 Calendar
;   1 - Royal - Inverted colors
;   2 - Dynamic - Inverted colors on January and February
;

Version=2

;Skin width in pixels
;Default is 400
Size=400